# Machine Learning
## Logistic Regression

In [1]:
import numpy as np

### Sigmoid Function

\begin{equation*}
\sigma(z) = \frac{1}{1 + e^{-z}}
\end{equation*}

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

### Loss Function (Cross Entropy)

\begin{equation*}
z = Wx + b
\end{equation*}

\begin{equation*}
y = \sigma(z)
\end{equation*}

\begin{equation*}
E(W, b) = -\sum_{i=1}^n [t_ilogy_i + (1 - t_i)log(1 - y_i)]
\end{equation*}

In [3]:
def loss_func(x, t):
    delta = 1e-7
    
    z = np.dot(x, W) + b
    y = sigmoid(z)
    
    return -np.sum(t * np.log(y + delta) + (1 - t) * np.log(1 - y + delta))

### Numerical Derivative

In [4]:
def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        
        x[idx] = tmp_val + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        
        grad[idx] = (fx1 - fx2) / (2 * delta_x)
        x[idx] = tmp_val
        
        it.iternext()
        
    return grad

### Error Function

In [5]:
def error_val(x, t):
    delta = 1e-7
    z = np.dot(x, W) + b
    y = sigmoid(z)
    
    return -np.sum(t * np.log(y + delta) + (1 - t) * np.log(1 - y + delta))

### Predict Function

In [6]:
def predict(x):
    z = np.dot(x, W) + b
    y = sigmoid(z)
    
    if y > 0.5:
        result = 1
    else:
        result = 0
    
    return y, result

### Simple Logistic Regression

In [7]:
x_data = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20]).reshape(10, 1)
t_data = np.array([0, 0, 0, 0,  0,  0,  1,  1,  1,  1]).reshape(10, 1)

In [8]:
W = np.random.rand(1, 1)
b = np.random.rand(1)

print("W =", W, ", W.shape =", W.shape, ", b =", b, ", b.shape =", b.shape)

W = [[0.69497129]] , W.shape = (1, 1) , b = [0.90006244] , b.shape = (1,)


In [9]:
learning_rate = 1e-2

f = lambda x : loss_func(x_data, t_data)

print("Initial error value =", error_val(x_data, t_data), ", Initial W =", W, "\n", ", b =", b)

for step in range(10001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    
    if step % 400 == 0:
        print("step =", step, ", error value =", error_val(x_data, t_data), ", W =", W, ", b =", b)

Initial error value = 34.71751541409416 , Initial W = [[0.69497129]] 
 , b = [0.90006244]
step = 0 , error value = 17.300397280053787 , W = [[0.27850482]] , b = [0.84481656]
step = 400 , error value = 3.2346735214279025 , W = [[0.43539925]] , b = [-4.08885979]
step = 800 , error value = 1.7877681589921726 , W = [[0.45233476]] , b = [-5.62735377]
step = 1200 , error value = 1.5202423407981431 , W = [[0.52992492]] , b = [-6.66055342]
step = 1600 , error value = 1.353983374659132 , W = [[0.59132297]] , b = [-7.47589585]
step = 2000 , error value = 1.237100414701151 , W = [[0.64293066]] , b = [-8.159724]
step = 2400 , error value = 1.148687663524711 , W = [[0.68789774]] , b = [-8.75450015]
step = 2800 , error value = 1.07848921356504 , W = [[0.72802405]] , b = [-9.28446706]
step = 3200 , error value = 1.0208010134068302 , W = [[0.76444249]] , b = [-9.76486786]
step = 3600 , error value = 0.9721606173216141 , W = [[0.79791627]] , b = [-10.20595983]
step = 4000 , error value = 0.930325927569

In [10]:
real_val, logical_val = predict(3)

print(real_val, logical_val)

[[1.12280024e-05]] 0


In [11]:
real_val, logical_val = predict(17)

print(real_val, logical_val)

[[0.99127883]] 1


### Multi-Variable Logistic Regression

In [12]:
x_data = np.array([ [2, 4], [4, 11], [6, 6], [8, 5], [10, 7], [12, 16], [14, 8], [16, 3], [18, 7] ])
t_data = np.array([0, 0, 0, 0, 1,  1,  1,  1,  1]).reshape(9, 1)

In [13]:
W = np.random.rand(2, 1)
b = np.random.rand(1)

print("W =", W, ", W.shape =", W.shape, ", b =", b, ", b.shape =", b.shape)

W = [[0.65533296]
 [0.3373819 ]] , W.shape = (2, 1) , b = [0.39590238] , b.shape = (1,)


In [14]:
learning_rate = 1e-2

f = lambda x : loss_func(x_data, t_data)

print("Initial error value =", error_val(x_data, t_data), ", Initial W =", W, "\n", ", b =", b)

for step in range(80001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    
    if step % 400 == 0:
        print("step =", step, ", error value =", error_val(x_data, t_data), ", W =", W, ", b =", b)

Initial error value = 23.511598133353278 , Initial W = [[0.65533296]
 [0.3373819 ]] 
 , b = [0.39590238]
step = 0 , error value = 12.906817724232392 , W = [[0.4564669 ]
 [0.07947629]] , b = [0.35841551]
step = 400 , error value = 2.2351653623960637 , W = [[ 0.42516798]
 [-0.08391828]] , b = [-2.69660667]
step = 800 , error value = 1.5762980959229111 , W = [[ 0.53973411]
 [-0.02486604]] , b = [-4.30827339]
step = 1200 , error value = 1.271896511038924 , W = [[0.62611875]
 [0.01002686]] , b = [-5.40792357]
step = 1600 , error value = 1.0930311022733026 , W = [[0.69597998]
 [0.03500104]] , b = [-6.25172539]
step = 2000 , error value = 0.9730334186582262 , W = [[0.75493336]
 [0.05494687]] , b = [-6.94306658]
step = 2400 , error value = 0.8855132279686828 , W = [[0.80608942]
 [0.07204814]] , b = [-7.53352357]
step = 2800 , error value = 0.8179317874637637 , W = [[0.85135358]
 [0.08743851]] , b = [-8.05237437]
step = 3200 , error value = 0.7635556894219244 , W = [[0.89198176]
 [0.10176519]] 

step = 31200 , error value = 0.17187399045228224 , W = [[1.77791827]
 [0.69978451]] , b = [-20.11935628]
step = 31600 , error value = 0.17001198748522062 , W = [[1.78430323]
 [0.70455428]] , b = [-20.20535399]
step = 32000 , error value = 0.16818935634620177 , W = [[1.79062278]
 [0.7092695 ]] , b = [-20.29043706]
step = 32400 , error value = 0.16640487130500164 , W = [[1.79687823]
 [0.7139314 ]] , b = [-20.3746245]
step = 32800 , error value = 0.16465735677849977 , W = [[1.80307085]
 [0.71854115]] , b = [-20.45793473]
step = 33200 , error value = 0.1629456847938977 , W = [[1.80920187]
 [0.72309987]] , b = [-20.54038565]
step = 33600 , error value = 0.1612687726047316 , W = [[1.81527248]
 [0.72760867]] , b = [-20.62199456]
step = 34000 , error value = 0.15962558044915034 , W = [[1.82128385]
 [0.73206861]] , b = [-20.70277829]
step = 34400 , error value = 0.15801510944045982 , W = [[1.8272371 ]
 [0.73648072]] , b = [-20.78275316]
step = 34800 , error value = 0.1564363995809115 , W = [[1.

step = 62800 , error value = 0.09181228845662563 , W = [[2.14745384]
 [0.96814943]] , b = [-25.05117566]
step = 63200 , error value = 0.09127126342467008 , W = [[2.15095224]
 [0.97063078]] , b = [-25.09751711]
step = 63600 , error value = 0.09073653115620575 , W = [[2.1544306 ]
 [0.97309707]] , b = [-25.14358817]
step = 64000 , error value = 0.0902079830705539 , W = [[2.15788915]
 [0.97554847]] , b = [-25.18939194]
step = 64400 , error value = 0.08968551306094051 , W = [[2.16132812]
 [0.97798516]] , b = [-25.23493149]
step = 64800 , error value = 0.08916901742464366 , W = [[2.16474772]
 [0.98040732]] , b = [-25.28020983]
step = 65200 , error value = 0.08865839479552051 , W = [[2.16814817]
 [0.98281511]] , b = [-25.3252299]
step = 65600 , error value = 0.0881535460787421 , W = [[2.17152968]
 [0.98520871]] , b = [-25.36999462]
step = 66000 , error value = 0.08765437438775726 , W = [[2.17489245]
 [0.98758828]] , b = [-25.41450684]
step = 66400 , error value = 0.08716078498326994 , W = [[2

In [15]:
test_data = np.array([3, 17])
predict(test_data)

(array([0.12868127]), 0)

In [16]:
test_data = np.array([5, 8])
predict(test_data)

(array([0.0009903]), 0)

In [17]:
test_data = np.array([7, 21])
predict(test_data)

(array([0.99998955]), 1)

In [18]:
test_data = np.array([12, 0])
predict(test_data)

(array([0.63499419]), 1)