# Deep Learning
## Neural Network

In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [3]:
def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        
        x[idx] = tmp_val + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        
        grad[idx] = (fx1 - fx2) / (2 * delta_x)
        x[idx] = tmp_val
        
        it.iternext()
    return grad

In [4]:
class LogicGate:
    def __init__(self, gate_name, xdata, tdata):
        self.name = gate_name
        
        self.__xdata = xdata.reshape(4, 2)
        self.__tdata = tdata.reshape(4, 1)
        
        self.__W2 = np.random.rand(2, 6)
        self.__b2 = np.random.rand(6)
        
        self.__W3 = np.random.rand(6, 1)
        self.__b3 = np.random.rand(1)
        
        self.__learning_rate = 1e-2
    
        print(self.name, "object is created")

    def feed_forward(self):
        delta = 1e-7
        
        z2 = np.dot(self.__xdata, self.__W2) + self.__b2
        a2 = sigmoid(z2)
        
        z3 = np.dot(a2, self.__W3) + self.__b3
        y = a3 = sigmoid(z3)
        
        return -np.sum(self.__tdata * np.log(y + delta) + (1 - self.__tdata) * np.log((1 - y) + delta))
    
    def loss_val(self):
        delta = 1e-7
        
        z2 = np.dot(self.__xdata, self.__W2) + self.__b2
        a2 = sigmoid(z2)
        
        z3 = np.dot(a2, self.__W3) + self.__b3
        y = a3 = sigmoid(z3)
        
        return -np.sum(self.__tdata * np.log(y + delta) + (1 - self.__tdata) * np.log((1 - y) + delta))
    
    def train(self):
        f = lambda x : self.feed_forward()
        
        print("Initial loss value =", self.loss_val())
        
        for step in range(10001):
            self.__W2 -= self.__learning_rate * numerical_derivative(f, self.__W2)
            self.__b2 -= self.__learning_rate * numerical_derivative(f, self.__b2)
            
            self.__W3 -= self.__learning_rate * numerical_derivative(f, self.__W3)
            self.__b3 -= self.__learning_rate * numerical_derivative(f, self.__b3)
            
            if step % 400 == 0:
                print("step =", step, "loss value =", self.loss_val())

    def predict(self, input_data):
        z2 = np.dot(input_data, self.__W2) + self.__b2
        a2 = sigmoid(z2)
        
        z3 = np.dot(a2, self.__W3) + self.__b3
        y = a3 = sigmoid(z3)
        
        if y > 0.5:
            result = 1
        else:
            result = 0
        
        return y, result

### AND Gate

In [5]:
xdata = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
tdata = np.array([0, 0, 0, 1])

and_obj = LogicGate("AND", xdata, tdata)
and_obj.train()

AND object is created
Initial loss value = 6.817373049995152
step = 0 loss value = 6.573398754855648
step = 400 loss value = 2.2703038105870004
step = 800 loss value = 2.1220320682891027
step = 1200 loss value = 1.9146317459777575
step = 1600 loss value = 1.636888582645165
step = 2000 loss value = 1.321914303942739
step = 2400 loss value = 1.0223670815101804
step = 2800 loss value = 0.7759119542476813
step = 3200 loss value = 0.591508056669505
step = 3600 loss value = 0.4595166274385759
step = 4000 loss value = 0.3657170213417306
step = 4400 loss value = 0.29815318079414244
step = 4800 loss value = 0.24840018787217044
step = 5200 loss value = 0.21087080644572284
step = 5600 loss value = 0.18190175870366682
step = 6000 loss value = 0.15906671722387475
step = 6400 loss value = 0.14072789855940854
step = 6800 loss value = 0.12575543557784902
step = 7200 loss value = 0.11335259346148535
step = 7600 loss value = 0.10294571681104356
step = 8000 loss value = 0.09411371269846135
step = 8400 lo

In [6]:
test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

for data in test_data:
    print(and_obj.predict(data))

(array([0.00169032]), 0)
(array([0.01540639]), 0)
(array([0.01659547]), 0)
(array([0.96960453]), 1)


### OR Gate

In [7]:
xdata = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
tdata = np.array([0, 1, 1, 1])

or_obj = LogicGate("OR", xdata, tdata)
or_obj.train()

OR object is created
Initial loss value = 2.2102239893700557
step = 0 loss value = 2.204864494967072
step = 400 loss value = 1.9412820119008956
step = 800 loss value = 1.7111373370501575
step = 1200 loss value = 1.3882910706748075
step = 1600 loss value = 1.0392320981171377
step = 2000 loss value = 0.748629349541852
step = 2400 loss value = 0.5415402629196583
step = 2800 loss value = 0.4025054484900657
step = 3200 loss value = 0.309416752158331
step = 3600 loss value = 0.24562166356646908
step = 4000 loss value = 0.20049433835862615
step = 4400 loss value = 0.16753304096747534
step = 4800 loss value = 0.14274034829714471
step = 5200 loss value = 0.12360238174033597
step = 5600 loss value = 0.10849280736052523
step = 6000 loss value = 0.09632856982540801
step = 6400 loss value = 0.08636829305262914
step = 6800 loss value = 0.07809147676688576
step = 7200 loss value = 0.07112420272482123
step = 7600 loss value = 0.06519223452972465
step = 8000 loss value = 0.060090659608437146
step = 840

In [8]:
test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

for data in test_data:
    print(or_obj.predict(data))

(array([0.02457307]), 0)
(array([0.99130785]), 1)
(array([0.99189247]), 1)
(array([0.99909536]), 1)


### NAND Gate

In [9]:
xdata = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
tdata = np.array([1, 1, 1, 0])

nand_obj = LogicGate("NAND", xdata, tdata)
nand_obj.train()

NAND object is created
Initial loss value = 3.5750971666806883
step = 0 loss value = 3.5381321440272506
step = 400 loss value = 2.298792177493607
step = 800 loss value = 2.1512553343993273
step = 1200 loss value = 1.8845541058120407
step = 1600 loss value = 1.4936929634354783
step = 2000 loss value = 1.1177565866056696
step = 2400 loss value = 0.8305257067637843
step = 2800 loss value = 0.6202409052995675
step = 3200 loss value = 0.4693793991425308
step = 3600 loss value = 0.36252112487439336
step = 4000 loss value = 0.28662384278537234
step = 4400 loss value = 0.23192376834449407
step = 4800 loss value = 0.19168447692397375
step = 5200 loss value = 0.16141872448179934
step = 5600 loss value = 0.1381563441090431
step = 6000 loss value = 0.11991378489247193
step = 6400 loss value = 0.1053448418471425
step = 6800 loss value = 0.09351830422806687
step = 7200 loss value = 0.08377721674772497
step = 7600 loss value = 0.07564912102141291
step = 8000 loss value = 0.06878800746627195
step = 84

In [10]:
test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

for data in test_data:
    print(nand_obj.predict(data))

(array([0.99997636]), 1)
(array([0.98944664]), 1)
(array([0.98870416]), 1)
(array([0.02404524]), 0)


### XOR Gate

In [11]:
xdata = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
tdata = np.array([0, 1, 1, 0])

xor_obj = LogicGate("XOR", xdata, tdata)
xor_obj.train()

XOR object is created
Initial loss value = 5.47693541648629
step = 0 loss value = 5.360099640414162
step = 400 loss value = 2.758455834302638
step = 800 loss value = 2.752811482316535
step = 1200 loss value = 2.744707453322649
step = 1600 loss value = 2.7329887454099198
step = 2000 loss value = 2.7160107755342033
step = 2400 loss value = 2.691489930430089
step = 2800 loss value = 2.656422158101111
step = 3200 loss value = 2.607376705300094
step = 3600 loss value = 2.541709430526528
step = 4000 loss value = 2.459650264732777
step = 4400 loss value = 2.3653411933322164
step = 4800 loss value = 2.264848271840707
step = 5200 loss value = 2.1627646971897945
step = 5600 loss value = 2.0603349664325727
step = 6000 loss value = 1.955506791874875
step = 6400 loss value = 1.8439273529699736
step = 6800 loss value = 1.7204902139028375
step = 7200 loss value = 1.5817170157530995
step = 7600 loss value = 1.4287083770519016
step = 8000 loss value = 1.2680430052670464
step = 8400 loss value = 1.10887

In [12]:
test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

for data in test_data:
    print(xor_obj.predict(data))

(array([0.10390617]), 0)
(array([0.85472717]), 1)
(array([0.87032209]), 1)
(array([0.18373043]), 0)
