# Python Libraries
## numpy

### How to use a library in python

In [1]:
import numpy
A = numpy.array([1, 2])
print("A ==", A, ", type ==", type(A))

A == [1 2] , type == <class 'numpy.ndarray'>


In [2]:
import numpy as np
A = np.array([1, 2])
print("A ==", A, ", type ==", type(A))

A == [1 2] , type == <class 'numpy.ndarray'>


In [3]:
from numpy import exp
result = exp(1)
print("result ==", result, ", type ==", type(result))

result == 2.718281828459045 , type == <class 'numpy.float64'>


In [4]:
from numpy import *
result = exp(1) + log(1.7) + sqrt(2)
print("result ==", result, ", type ==", type(result))

result == 4.663123641894311 , type == <class 'numpy.float64'>


### numpy array vs list

In [5]:
# list
A = [ [1, 0], [0, 1] ]
B = [ [1, 1], [1, 1] ]

A + B

[[1, 0], [0, 1], [1, 1], [1, 1]]

In [6]:
# numpy matrix
A = np.array([ [1, 0], [0, 1] ])
B = np.array([ [1, 1], [1, 1] ])

A + B

array([[2, 1],
       [1, 2]])

### numpy vector

In [7]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print("A ==", A, ", B ==", B)

print("A.shape ==", A.shape, ", B.shape ==", B.shape)

print("A.ndim ==", A.ndim, ", B.ndim ==", B.ndim)

A == [1 2 3] , B == [4 5 6]
A.shape == (3,) , B.shape == (3,)
A.ndim == 1 , B.ndim == 1


In [8]:
# element-wise operation

print("A + B ==", A + B)
print("A - B ==", A - B)
print("A * B ==", A * B)
print("A / B ==", A / B)

A + B == [5 7 9]
A - B == [-3 -3 -3]
A * B == [ 4 10 18]
A / B == [0.25 0.4  0.5 ]


### numpy matrix

In [9]:
A = np.array([ [1, 2, 3], [4, 5, 6] ])
B = np.array([ [-1, -2, -3], [-4, -5, -6] ])

print("A.shape ==", A.shape, ", B.shape ==", B.shape)

print("A.ndim ==", A.ndim, ", B.ndim ==", B.ndim)

A.shape == (2, 3) , B.shape == (2, 3)
A.ndim == 2 , B.ndim == 2


In [10]:
C = np.array([1, 2, 3])
print("C.shape ==", C.shape)

C = C.reshape(1, 3)
print("C.shape ==", C.shape)

C.shape == (3,)
C.shape == (1, 3)


### numpy dot product

In [11]:
A = np.array([ [1, 2, 3], [4, 5, 6] ])
B = np.array([ [-1, -2], [-3, -4], [-5, -6] ])

C = np.dot(A, B)

print("A.shape ==", A.shape, ", B.shape ==", B.shape)
print("C.shape ==", C.shape)
print(C)

A.shape == (2, 3) , B.shape == (3, 2)
C.shape == (2, 2)
[[-22 -28]
 [-49 -64]]


### numpy broadcast

In [12]:
A = np.array([ [1, 2], [3, 4] ])
b = 5

print(A + b)

[[6 7]
 [8 9]]


In [13]:
C = np.array([ [1, 2], [3, 4] ])
D = np.array([4, 5])

print(C + D)

[[5 7]
 [7 9]]


### numpy transpose

In [14]:
A = np.array([ [1, 2], [3, 4], [5, 6] ])
B = A.T

print("A.shape ==", A.shape, ", B.shape ==", B.shape)
print(A)
print(B)

A.shape == (3, 2) , B.shape == (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


### numpy matrix indexing / slicing

In [15]:
C = np.array([1, 2, 3, 4, 5])
D = C.T

E = C.reshape(1, 5)
F = E.T

print("C.shape ==", C.shape, ", D.shape ==", D.shape)
print("E.shape ==", E.shape, ", F.shape ==", F.shape)
print(F)

C.shape == (5,) , D.shape == (5,)
E.shape == (1, 5) , F.shape == (5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [16]:
A = np.array([10, 20, 30, 40, 50, 60]).reshape(3, 2)
print("A.shape ==", A.shape)
print(A)

A.shape == (3, 2)
[[10 20]
 [30 40]
 [50 60]]


In [17]:
print("A[0, 0] ==", A[0, 0], ", A[0][0] ==", A[0][0])
print("A[2, 1] ==", A[2, 1], ", A[2][1] ==", A[2][1])

A[0, 0] == 10 , A[0][0] == 10
A[2, 1] == 60 , A[2][1] == 60


In [18]:
print("A[0:-1, 1:2] ==", A[0:-1, 1:2])

A[0:-1, 1:2] == [[20]
 [40]]


In [19]:
print("A[:, 0] ==", A[:, 0])
print("A[:, :] ==", A[:, :])

A[:, 0] == [10 30 50]
A[:, :] == [[10 20]
 [30 40]
 [50 60]]


### numpy matrix iterator

In [20]:
import numpy as np

A = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(A, "\n")
print("A.shape ==", A.shape, "\n")

it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])

while not it.finished:
    idx = it.multi_index
    
    print("current value =>", A[idx])
    
    it.iternext()

[[10 20 30 40]
 [50 60 70 80]] 

A.shape == (2, 4) 

current value => 10
current value => 20
current value => 30
current value => 40
current value => 50
current value => 60
current value => 70
current value => 80


### numpy.loadtxt( )

In [21]:
loaded_data = np.loadtxt('./data-01.csv', delimiter=',', dtype=np.float32)

x_data = loaded_data[:, :-1]
t_data = loaded_data[:, [-1]]

print("x_data.ndim ==", x_data.ndim, "x.shape ==", x_data.shape)
print("x_data ==", x_data)
print("t_data.ndim ==", t_data.ndim, "t.shape ==", t_data.shape)
print("t_data ==", t_data)

x_data.ndim == 2 x.shape == (25, 3)
x_data == [[73. 80. 75.]
 [93. 88. 93.]
 [89. 91. 90.]
 [96. 98. 90.]
 [73. 66. 70.]
 [53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]]
t_data.ndim == 2 t.shape == (25, 1)
t_data == [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


### numpy.random.rand( )

In [22]:
random_number1 = np.random.rand(3)
random_number2 = np.random.rand(1, 3)
random_number3 = np.random.rand(3, 1)

print("random_number1 ==", random_number1, ", random_number1.shape ==", random_number1.shape)
print("random_number2 ==", random_number2, ", random_number2.shape ==", random_number2.shape)
print("random_number3 ==", random_number3, ", random_number3.shape ==", random_number3.shape)

random_number1 == [0.47297852 0.76289942 0.93675297] , random_number1.shape == (3,)
random_number2 == [[0.94649664 0.05641899 0.37506415]] , random_number2.shape == (1, 3)
random_number3 == [[0.2163584 ]
 [0.03972625]
 [0.68741121]] , random_number3.shape == (3, 1)


### numpy.sum( ), numpy.exp( ), numpy.log( )

In [23]:
X = np.array([2, 4, 6, 8])

print("np.sum(X) ==", np.sum(X))
print("np.exp(X) ==", np.exp(X))
print("np.log(X) ==", np.log(X))

np.sum(X) == 20
np.exp(X) == [   7.3890561    54.59815003  403.42879349 2980.95798704]
np.log(X) == [0.69314718 1.38629436 1.79175947 2.07944154]


### numpy.max( ), numpy.min( ), numpy.argmax( ), numpy.argmin( )

In [24]:
X = array([2, 4, 6, 8])

print("np.max(X) ==", np.max(X))
print("np.min(X) ==", np.min(X))
print("np.argmax(X) ==", np.argmax(X))
print("np.argmin(X) ==", np.argmin(X))

np.max(X) == 8
np.min(X) == 2
np.argmax(X) == 3
np.argmin(X) == 0


In [25]:
X = np.array([[2, 4, 6], [1, 2, 3], [0, 5, 8]])

print("np.max(X) ==", np.max(X, axis=0))
print("np.min(X) ==", np.min(X, axis=0))

print("np.max(X) ==", np.max(X, axis=1))
print("np.min(X) ==", np.min(X, axis=1))

print("np.argmax(X) ==", np.argmax(X, axis=0))
print("np.argmin(X) ==", np.argmin(X, axis=0))

print("np.argmax(X) ==", np.argmax(X, axis=1))
print("np.argmin(X) ==", np.argmin(X, axis=1))

np.max(X) == [2 5 8]
np.min(X) == [0 2 3]
np.max(X) == [6 3 8]
np.min(X) == [2 1 0]
np.argmax(X) == [0 2 2]
np.argmin(X) == [2 1 1]
np.argmax(X) == [2 2 2]
np.argmin(X) == [0 0 0]


### numpy.ones( ), numpy.zeros( )

In [26]:
A = np.ones([3, 3])
print("A.shap ==", A.shape, "A ==", A)
B = np.zeros([3, 2])
print("B.shape ==", B.shape, "B ==", B)

A.shap == (3, 3) A == [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B.shape == (3, 2) B == [[0. 0.]
 [0. 0.]
 [0. 0.]]
